# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [1]:
s="Hi there Sam!"
s=s.split()
print(s)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [2]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [3]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2]
print(a)

['hello']


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [10]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr = np.concatenate((a, b))
arr

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd


In [26]:
A = np.random.randint(8, size=(3,2))
A
df = pd.DataFrame(A)
df

0  1
0  6  3
1  1  6
2  4  1

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [28]:
dRan3 = pd.date_range(start ='01-01-2023', 
            end ='10-02-2023', periods = 13)
dRan3

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-23 20:00:00',
               '2023-02-15 16:00:00', '2023-03-10 12:00:00',
               '2023-04-02 08:00:00', '2023-04-25 04:00:00',
               '2023-05-18 00:00:00', '2023-06-09 20:00:00',
               '2023-07-02 16:00:00', '2023-07-25 12:00:00',
               '2023-08-17 08:00:00', '2023-09-09 04:00:00',
               '2023-10-02 00:00:00'],
              dtype='datetime64[ns]', freq=None)

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [19]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [21]:
df = pd.DataFrame(lists) 
print(df )

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
